(function(){
  "use strict";
  const D=window.XIAOLUO_ACTIONS||{actions:[],moodCategories:[],bodyStates:[],advancedFilters:{},focalComparisons:[],lightingGuides:[],cameraGuides:[],safetyRules:[]};
  const FILTERS=[['shotType','景别'],['focalLength','焦段'],['prop','道具'],['cameraAngle','机位'],['lighting','打光']];
  const FOCAL_GUIDES={
    '16mm':{title:'超广角',image:'assets/cos-actions/focal-guides/focal-16mm.png',cue:'强烈近大远小 · 地面线快速汇聚'},
    '24mm':{title:'广角',image:'assets/cos-actions/focal-guides/focal-24mm.png',cue:'双向透视 · 动作张力与环境并重'},
    '35mm':{title:'全身环境',image:'assets/cos-actions/focal-guides/focal-35mm.png',cue:'自然纵深 · 人物与空间比例均衡'},
    '50mm':{title:'标准视角',image:'assets/cos-actions/focal-guides/focal-50mm.png',cue:'温和汇聚 · 接近自然观看'},
    '85mm':{title:'中长焦',image:'assets/cos-actions/focal-guides/focal-85mm.png',cue:'背景拉近 · 空间开始压缩'},
    '135mm':{title:'长焦压缩',image:'assets/cos-actions/focal-guides/focal-135mm.png',cue:'层次叠合 · 地面线趋近平行'}
  };
  const FAV_KEY='xiaoluo-action-favorites-v2';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const readFav=()=>{try{return new Set(JSON.parse(localStorage.getItem(FAV_KEY)||'[]'))}catch(_){return new Set()}};
  const state={tab:'library',reference:'focal',focalGroup:'16mm',query:'',mood:'',filters:{},favorites:readFav(),similarId:'',suggestions:false};
  const byId=Object.fromEntries(D.actions.map(x=>[x.id,x]));
  const copyIcon='<svg width="15" height="15" viewBox="0 0 24 24" fill="none"><rect x="8" y="8" width="11" height="11" rx="2" stroke="currentColor" stroke-width="1.7"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2" stroke="currentColor" stroke-width="1.7"/></svg>';
  function copyText(text){
    if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(text).catch(()=>fallback(text));else fallback(text);
    document.dispatchEvent(new CustomEvent('xiaoluo-toast',{detail:'已复制动作说明'}));
  }
  function fallback(text){const a=document.createElement('textarea');a.value=text;a.style.cssText='position:fixed;opacity:0';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}
  function description(item){return `${item.title} / ${item.englishTitle}\n动作：${item.description}\n身体状态：${item.bodyState}\n焦段：${item.focalLength}\n景别：${item.shotType}\n机位：${item.cameraAngle}\n透视：${item.perspectiveFeatures}\n道具：${item.prop}\n打光：${item.lighting}\n动作提示：${item.poseTips}\n常见错误：${item.commonMistakes}`}
  function filtered(){
    const q=state.query.trim().toLowerCase();
    return D.actions.filter(x=>{
      if(state.tab==='favorites'&&!state.favorites.has(x.id))return false;
      if(state.mood&&x.mood!==state.mood)return false;
      for(const [k,v] of Object.entries(state.filters))if(v&&x[k]!==v)return false;
      if(state.similarId){const b=byId[state.similarId];if(b&&x.id!==b.id&&x.mood!==b.mood&&x.bodyState!==b.bodyState)return false}
      if(q&&!([x.title,x.englishTitle,x.mood,x.bodyState,x.subcategory,x.description,x.focalLength,x.prop,x.cameraAngle,x.lighting].join(' ').toLowerCase().includes(q)))return false;
      return true;
    });
  }
  function syncUrl(){
    const p=new URLSearchParams();
    if(state.tab!=='library')p.set('actionTab',state.tab);if(state.reference!=='focal')p.set('ref',state.reference);if(state.query)p.set('aq',state.query);if(state.mood)p.set('mood',state.mood);
    for(const [k,v] of Object.entries(state.filters))if(v)p.set(k,v);
    const url=location.pathname+(p.toString()?`?${p}`:'')+location.hash;try{history.replaceState({...history.state,xiaoluo:true,section:'poses'},'',url)}catch(_){ }
  }
  function restoreUrl(){const p=new URLSearchParams(location.search);state.tab=p.get('actionTab')||'library';state.reference=p.get('ref')||'focal';state.query=p.get('aq')||'';state.mood=p.get('mood')||'';for(const [k] of FILTERS){const v=p.get(k);if(v)state.filters[k]=v}}
  function suggestions(){
    const q=state.query.trim().toLowerCase();if(!q)return '';
    const actions=D.actions.filter(x=>`${x.title} ${x.englishTitle}`.toLowerCase().includes(q)).slice(0,5);
    const moods=D.moodCategories.filter(x=>x.name.includes(state.query)).slice(0,4);
    const filters=[];for(const [k,label] of FILTERS)for(const v of D.advancedFilters[k]||[])if(v.toLowerCase().includes(q))filters.push({k,label,v});
    const group=(title,items,kind)=>items.length?`<div class="action-suggest-group"><b>${title}</b>${items.map(x=>kind==='action'?`<button class="action-suggest" data-action-open="${x.id}"><span>${esc(x.title)}</span><small>${esc(x.bodyState)} · ${esc(x.focalLength)}</small></button>`:kind==='mood'?`<button class="action-suggest" data-action-mood="${esc(x.name)}"><span>${esc(x.name)}</span><small>动作类型</small></button>`:`<button class="action-suggest" data-action-filter-key="${x.k}" data-action-filter-value="${esc(x.v)}"><span>${esc(x.v)}</span><small>${esc(x.label)}</small></button>`).join('')}</div>`:'';
    const html=group('动作',actions,'action')+group('动作类型',moods,'mood')+group('筛选',filters.slice(0,5),'filter');
    return html||`<div class="action-suggest-group"><b>没有匹配建议</b></div>`;
  }
  function hero(){const libraryActive=state.tab!=='reference';return `<div class="action-hero"><p class="action-crumb">小洛 / COS 动作大全</p><div class="action-hero-row"><div><h1>COS 动作大全</h1><p class="action-hero-sub">从动作类型或焦段进入，快速找到适合的动作参考。每个动作只归属于一个焦段，不会在其他焦段重复出现；所有正式参考图均为无身份高细节线稿人偶。</p><p class="action-inline-stats">已收录 ${D.actions.length} 个动作 · ${D.moodCategories.length} 种动作类型 · ${(D.advancedFilters.focalLength||[]).length} 个独立焦段库 · 持续更新</p></div></div><nav class="action-primary-categories" aria-label="动作查找方式"><button data-action-mode="type" data-action-tab="library" class="${libraryActive?'active':''}"><i>01</i><span><strong>按动作类型查找</strong><small>从角色风格和动作表达进入</small></span><b>→</b></button><button data-action-mode="focal" data-action-tab="reference" class="${state.tab==='reference'?'active':''}"><i>02</i><span><strong>按焦段查找</strong><small>查看各焦段专属且不重复的动作</small></span><b>→</b></button></nav><div class="action-search-panel"><div class="action-search-box"><input data-action-query type="search" autocomplete="off" value="${esc(state.query)}" placeholder="搜索动作名称、姿势、动作类型或关键词…"><span class="action-search-icon">⌕</span><div class="action-suggestions" ${state.suggestions&&state.query?'':'hidden'}>${suggestions()}</div></div><button class="action-search-cta" data-action-start>${state.tab==='reference'?'浏览焦段动作':'开始选动作'}</button></div><div class="action-hot"><span>热门：</span>${['可爱','战斗','高冷','双人','坐姿','超广角'].map(x=>`<button data-action-hot="${x}">${x}</button>`).join('')}</div></div>`}
  function typeStep(){return `<section class="action-step" id="actionType"><div class="action-step-head"><div><p>ACTION TYPE</p><h2>选择动作类型</h2></div><span>${state.mood?`已选择：${esc(state.mood)}`:'可跳过，直接查看全部'}</span></div><div class="action-moods">${D.moodCategories.map((x,i)=>{const cover=D.actions.find(a=>a.mood===x.name)?.image||'';return `<button class="action-mood ${state.mood===x.name?'active':''}" data-action-mood="${esc(x.name)}"><img src="${esc(cover)}" alt="" loading="lazy"><i>${String(i+1).padStart(2,'0')} · ${D.actions.filter(a=>a.mood===x.name).length} POSES</i><strong>${esc(x.name)}</strong><span>${esc(x.description)}</span></button>`}).join('')}</div></section>`}
  function activeFilters(){const values=[];if(state.mood)values.push(['mood',state.mood]);for(const [k,v] of Object.entries(state.filters))if(v)values.push([k,v]);return values.length?`<div class="action-active-filters">${values.map(([k,v])=>`<button data-action-remove-filter="${k}">${esc(v)} ×</button>`).join('')}</div>`:''}
  function card(x,index,options={}){const visual=options.image||x.image,kind=options.kind||'type',alt=kind==='focal'?`${x.alt}，${x.focalLength}地面与空间透视参考`:x.alt;return `<article class="action-card" data-action-image-kind="${kind}"><div class="action-card-image"><img src="${esc(visual)}" alt="${esc(alt)}" loading="lazy"><span class="action-card-number">${String(index+1).padStart(2,'0')}</span><button class="action-fav ${state.favorites.has(x.id)?'active':''}" data-action-favorite="${x.id}" aria-label="收藏${esc(x.title)}">${state.favorites.has(x.id)?'♥':'♡'}</button></div><div class="action-card-body"><div class="action-card-kicker"><span>${esc(x.mood)}</span><span>${esc(x.bodyState)}</span></div><h3>${esc(x.title)}</h3><div class="action-card-en">${esc(x.englishTitle)}</div><div class="action-card-tags"><span>${esc(x.focalLength)}</span><span>${esc(x.shotType)}</span><span>${esc(x.cameraAngle)}</span></div><div class="action-card-actions"><button data-action-open="${x.id}">查看详情</button><button title="复制动作说明" data-action-copy="${x.id}">${copyIcon}</button><button class="action-similar" data-action-similar="${x.id}">相似</button></div></div></article>`}
  function results(){const list=filtered(),favoriteButton=state.tab==='favorites'?'<button class="action-view-favorites" data-action-tab="library">返回全部动作</button>':`<button class="action-view-favorites" data-action-tab="favorites">我的收藏${state.favorites.size?` · ${state.favorites.size}`:''}</button>`;return `<section class="action-stage"><div class="action-result-bar"><div><h2>${state.tab==='favorites'?'我的收藏':'动作结果'}</h2><p>${list.length} 个动作${state.similarId?' · 正在显示相似动作':''}</p></div><div class="action-result-actions">${state.similarId?'<button class="action-clear" data-action-clear-similar>退出相似</button>':''}${favoriteButton}<button class="action-filter-open" data-action-filter-open>高级筛选 · ${Object.values(state.filters).filter(Boolean).length}</button></div></div>${activeFilters()}<div class="action-grid">${list.length?list.map(card).join(''):`<div class="action-empty"><strong>暂时没有符合条件的动作</strong>清除部分筛选条件或收藏一些动作后再查看。</div>`}</div></section>`}
  function library(){return `<div class="action-stage">${state.tab==='library'?typeStep():''}${results()}</div>`}
  function reference(){const focals=D.advancedFilters.focalLength||[];const items=D.actions.filter(x=>x.focalLength===state.focalGroup),guide=FOCAL_GUIDES[state.focalGroup]||{};return `<section id="actionFocal"><div class="reference-intro"><h2>按焦段查找</h2><p>从超广角的强汇聚到长焦的空间压缩，每张线稿都加入了地面网格、消失线和建筑尺度参照。六个焦段使用不同动作，不会重复出现。</p></div><div class="focal-guide-grid">${focals.map(id=>{const g=FOCAL_GUIDES[id]||{};return `<button data-action-focal-group="${id}" class="focal-guide ${state.focalGroup===id?'active':''}"><span class="focal-guide-image"><img src="${esc(g.image||'')}" alt="${esc(id)} 焦段透视线稿参考" loading="lazy"></span><span class="focal-guide-copy"><i>${esc(id)}</i><strong>${esc(g.title||id)}</strong><small>${esc(g.cue||'')}</small><b>${D.actions.filter(x=>x.focalLength===id).length} 个专属动作</b></span></button>`}).join('')}</div><div class="focal-groups">${focals.map(id=>`<button data-action-focal-group="${id}" class="${state.focalGroup===id?'active':''}">${esc(id)} · ${D.actions.filter(x=>x.focalLength===id).length}</button>`).join('')}</div><div class="reference-intro focal-selection"><h2>${esc(state.focalGroup)} · ${esc(guide.title||'专属动作')}</h2><p>${esc(guide.cue||'')}。下方动作只归属于 ${esc(state.focalGroup)}，切换焦段会显示另一组不同动作。</p></div><div class="action-grid">${items.map((x,i)=>card(x,i,{image:x.focalImage,kind:'focal'})).join('')}</div></section>`}
  function drawer(){return `<div class="action-drawer-backdrop" data-action-filter-close></div><aside class="action-drawer" aria-label="高级筛选"><div class="action-drawer-head"><h2>高级筛选</h2><button class="action-drawer-close" data-action-filter-close>×</button></div>${FILTERS.map(([k,label])=>`<section class="action-filter-group"><b>${label}</b><div><button data-action-filter-key="${k}" data-action-filter-value="" class="${!state.filters[k]?'active':''}">全部</button>${(D.advancedFilters[k]||[]).map(v=>`<button data-action-filter-key="${k}" data-action-filter-value="${esc(v)}" class="${state.filters[k]===v?'active':''}">${esc(v)}</button>`).join('')}</div></section>`).join('')}<div class="action-drawer-foot"><button data-action-reset>清空</button><button data-action-filter-close>查看结果</button></div></aside>`}
  function view(){return `<section class="action-shell">${hero()}<div class="action-content">${state.tab==='reference'?reference():library()}</div>${drawer()}<button class="pose-top" data-action-top aria-label="返回顶部">↑</button></section>`}
  function render(keepScroll=true){const host=document.getElementById('content');if(!host||!host.querySelector('.action-shell'))return;const y=scrollY;host.innerHTML=view();if(keepScroll)scrollTo(0,y);syncUrl()}
  function setFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem(FAV_KEY,JSON.stringify([...state.favorites]));render()}
  function details(item){const row=(a,b,wide=false,safety=false)=>`<div class="pose-detail ${wide?'wide':''} ${safety?'action-safety':''}"><b>${a}</b><span>${esc(b)}</span></div>`;return `<p class="action-detail-note">${esc(item.description)}</p><div class="pose-detail-grid">${row('动作类型',item.mood)}${row('身体状态',item.bodyState)}${row('推荐焦段',item.focalLength)}${row('建议景别',item.shotType)}${row('建议机位',item.cameraAngle)}${row('拍摄距离',item.cameraDistance)}${row('透视特点',item.perspectiveFeatures,true)}${row('道具',item.prop)}${row('建议打光',item.lighting)}${row('前景提示',item.foregroundDescription,true)}${row('背景提示',item.backgroundDescription,true)}${row('动作重点',item.poseTips,true)}${row('常见错误',item.commonMistakes,true,true)}</div><div class="action-detail-tools"><button class="primary" data-action-copy="${item.id}">复制完整动作说明</button><button data-action-similar="${item.id}">查找相似动作</button><button data-action-favorite="${item.id}">${state.favorites.has(item.id)?'取消收藏':'收藏动作'}</button></div>`}
  function origin(trigger,dialog){const t=dialog.getBoundingClientRect(),s=trigger?.getBoundingClientRect?.();if(!s)return{transform:'translate3d(0,24px,0) scale(.82,.25)',radius:'20px'};const dx=s.left+s.width/2-(t.left+t.width/2),dy=s.top+s.height/2-(t.top+t.height/2);return{transform:`translate3d(${dx}px,${dy}px,0) scale(${Math.max(.14,s.width/t.width)},${Math.max(.08,s.height/t.height)})`,radius:getComputedStyle(trigger).borderRadius||'18px'}}
  function open(id,trigger,options={}){const item=byId[id],modal=document.getElementById('poseModal');if(!item||!modal)return;const dialog=modal.querySelector('.pose-dialog'),o=origin(trigger,dialog),visual=state.tab==='reference'&&item.focalImage?item.focalImage:item.image;modal.dataset.actionOpen=id;document.getElementById('poseModalTag').textContent=`${item.mood} · ${item.bodyState}`;document.getElementById('poseModalTitle').textContent=item.title;document.getElementById('poseModalEnglish').textContent=item.englishTitle;document.getElementById('poseModalVisual').innerHTML=`<img src="${esc(visual)}" alt="${esc(item.alt)}">`;document.getElementById('poseModalDetails').innerHTML=details(item);modal.classList.add('show','motion-active');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open','modal-visible');const backdrop=modal.querySelector('.prompt-modal-backdrop');if(dialog.animate){dialog.animate([{transform:o.transform,opacity:.06,borderRadius:o.radius},{transform:'translate3d(0,6px,0) scale(.985,1.01)',opacity:1,offset:.78},{transform:'none',opacity:1,borderRadius:'28px'}],{duration:620,easing:'cubic-bezier(.16,1,.3,1)',fill:'both'});backdrop.animate([{opacity:0,backdropFilter:'blur(0px)'},{opacity:1,backdropFilter:'blur(10px)'}],{duration:560,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'})}if(!options.fromHistory)history.pushState({xiaoluo:true,section:'poses',action:id},'');requestAnimationFrame(()=>modal.querySelector('.modal-close')?.focus())}
  async function close(){const modal=document.getElementById('poseModal');if(!modal?.classList.contains('show'))return;const dialog=modal.querySelector('.pose-dialog'),backdrop=modal.querySelector('.prompt-modal-backdrop');if(dialog.animate){await Promise.all([dialog.animate([{transform:'none',opacity:1},{transform:'translate3d(0,18px,0) scale(.82,.32)',opacity:0}],{duration:410,easing:'cubic-bezier(.4,0,.8,.2)'}).finished.catch(()=>{}),backdrop.animate([{opacity:1,backdropFilter:'blur(10px)'},{opacity:0,backdropFilter:'blur(0px)'}],{duration:390,easing:'ease'}).finished.catch(()=>{})])}modal.classList.remove('show','motion-active');modal.setAttribute('aria-hidden','true');delete modal.dataset.actionOpen;document.body.classList.remove('modal-open','modal-visible')}
  function requestClose(){if(history.state?.action)history.back();else close()}
  function click(e){
    const t=e.target.closest('[data-action-tab],[data-action-mood],[data-action-open],[data-action-copy],[data-action-favorite],[data-action-similar],[data-action-filter-open],[data-action-filter-close],[data-action-filter-key],[data-action-remove-filter],[data-action-reset],[data-action-reference],[data-action-focal-group],[data-action-start],[data-action-hot],[data-action-top],[data-action-clear-similar]');if(!t)return;
    if(t.dataset.actionTab){state.tab=t.dataset.actionTab;state.similarId='';render(false);setTimeout(()=>{const target=state.tab==='reference'?document.getElementById('actionFocal'):state.tab==='library'?document.getElementById('actionType'):document.querySelector('.action-result-bar');target?.scrollIntoView({behavior:'smooth',block:'start'})},40)}
    else if(t.dataset.actionMood!==undefined){state.mood=state.mood===t.dataset.actionMood?'':t.dataset.actionMood;state.suggestions=false;render()}
    else if(t.dataset.actionOpen)open(t.dataset.actionOpen,t)
    else if(t.dataset.actionCopy)copyText(description(byId[t.dataset.actionCopy]))
    else if(t.dataset.actionFavorite)setFav(t.dataset.actionFavorite)
    else if(t.dataset.actionSimilar){state.similarId=t.dataset.actionSimilar;requestClose();state.tab='library';render(false);setTimeout(()=>document.querySelector('.action-result-bar')?.scrollIntoView({behavior:'smooth'}),80)}
    else if(t.hasAttribute('data-action-filter-open')){document.body.classList.add('action-drawer-open');history.pushState({...history.state,actionDrawer:true},'')}
    else if(t.hasAttribute('data-action-filter-close')){document.body.classList.remove('action-drawer-open')}
    else if(t.dataset.actionFilterKey){state.filters[t.dataset.actionFilterKey]=t.dataset.actionFilterValue;state.suggestions=false;render()}
    else if(t.dataset.actionRemoveFilter){const k=t.dataset.actionRemoveFilter;k==='mood'?state.mood='':state.filters[k]='';render()}
    else if(t.hasAttribute('data-action-reset')){state.filters={};state.mood='';state.query='';render()}
    else if(t.dataset.actionReference){state.reference=t.dataset.actionReference;render()}
    else if(t.dataset.actionFocalGroup){state.focalGroup=t.dataset.actionFocalGroup;render()}
    else if(t.hasAttribute('data-action-start'))(state.tab==='reference'?document.getElementById('actionFocal'):state.tab==='favorites'?document.querySelector('.action-result-bar'):document.getElementById('actionType'))?.scrollIntoView({behavior:'smooth',block:'start'})
    else if(t.dataset.actionHot){state.query=t.dataset.actionHot;state.suggestions=false;render()}
    else if(t.hasAttribute('data-action-top'))scrollTo({top:0,behavior:'smooth'})
    else if(t.hasAttribute('data-action-clear-similar')){state.similarId='';render()}
  }
  function input(e){if(!e.target.matches('[data-action-query]'))return;state.query=e.target.value;state.suggestions=true;render();requestAnimationFrame(()=>document.querySelector('[data-action-query]')?.focus())}
  function mount(){restoreUrl();const host=document.getElementById('content');if(host)host.innerHTML=view()}
  document.addEventListener('click',click);document.addEventListener('input',input);document.addEventListener('xiaoluo-toast',e=>{const t=document.getElementById('toast');if(!t)return;t.textContent=e.detail;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)});
  window.addEventListener('popstate',event=>{
    if(document.body.classList.contains('action-drawer-open')&&!event.state?.actionDrawer)document.body.classList.remove('action-drawer-open');
    const modal=document.getElementById('poseModal');
    if(modal?.dataset.actionOpen&&!event.state?.action)close();
  });
  window.XIAOLUO_ACTION_APP={view,mount,open,close,requestClose,searchCard:(x,i)=>card(x,i)};
})();
